/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingIndexRouteImport } from './routes/booking/index'
import { Route as BookingCreateBookingRouteImport } from './routes/booking/createBooking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIndexRoute = BookingIndexRouteImport.update({
  id: '/booking/',
  path: '/booking/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCreateBookingRoute = BookingCreateBookingRouteImport.update({
  id: '/booking/createBooking',
  path: '/booking/createBooking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking/createBooking': typeof BookingCreateBookingRoute
  '/booking': typeof BookingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking/createBooking': typeof BookingCreateBookingRoute
  '/booking': typeof BookingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking/createBooking': typeof BookingCreateBookingRoute
  '/booking/': typeof BookingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/booking/createBooking' | '/booking'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/booking/createBooking' | '/booking'
  id: '__root__' | '/' | '/booking/createBooking' | '/booking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingCreateBookingRoute: typeof BookingCreateBookingRoute
  BookingIndexRoute: typeof BookingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/': {
      id: '/booking/'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/createBooking': {
      id: '/booking/createBooking'
      path: '/booking/createBooking'
      fullPath: '/booking/createBooking'
      preLoaderRoute: typeof BookingCreateBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingCreateBookingRoute: BookingCreateBookingRoute,
  BookingIndexRoute: BookingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
